---
- hosts: all
  tasks:
    - name: install package by win_package
      win_package:
        path: "https://www.nliteos.com/download/nLite-1.4.9.3.setup.exe"
        state: present
        arguments: '/install /norestart'
